services:
  db:
    container_name: jesse-earle-postgres
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      - psql:/var/lib/postgresql/data
    ports:
      - 5432:5432
volumes:
  psql:
